name:                drasil-build
version:             0.1.1.0
license:             BSD3
author:              "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith"
maintainer:          "Jacques Carette"
synopsis:	           A framework for code and document generation for scientific software - Build System SubPackage
github:              JacquesCarette/Drasil
homepage:            https://jacquescarette.github.io/Drasil/

extra-source-files: []

# Metadata used when publishing your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

dependencies:
- base >= 4.7 && < 5
- pretty >= 1.1.1.1
- drasil-lang

ghc-options:
- -Wall
- -Wredundant-constraints

library:
  source-dirs: ./
  exposed-modules:
  - Build.Drasil
