name:                drasil-data
version:             0.1.13.0
license:             BSD3
author:              "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith"
maintainer:          "Jacques Carette"
synopsis:	           A framework for code and document generation for scientific software - Data System SubPackage
github:              JacquesCarette/Drasil
homepage:            https://jacquescarette.github.io/Drasil/

extra-source-files: []

# Metadata used when publishing your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

dependencies:
- base >= 4.7 && < 5
- lens >= 4.12
- containers >= 0.5.5.1
- pretty >= 1.1.1.1
- mtl >= 2.2.1
- directory >= 1.2.6.2
- split >= 0.2.3.1
- MissingH >= 1.4.0.1
- parsec >= 3.1.9
- data-fix (>= 0.0.4 && <= 1.0)
- Decimal >= 0.5.1
- drasil-code
- drasil-gool
- drasil-lang
- drasil-theory
- drasil-utils

ghc-options:
- -Wall
- -Wredundant-constraints

library:
  source-dirs: ./
  exposed-modules:
  - Data.Drasil.People
  - Data.Drasil.Citations
  - Data.Drasil.Constraints
  - Data.Drasil.SI_Units
  - Data.Drasil.Concepts.Computation
  - Data.Drasil.Concepts.Documentation
  - Data.Drasil.Concepts.Thermodynamics
  - Data.Drasil.Concepts.PhysicalProperties
  - Data.Drasil.Concepts.Education
  - Data.Drasil.Concepts.Physics
  - Data.Drasil.Concepts.Software
  - Data.Drasil.Concepts.Math
  - Data.Drasil.Concepts.SolidMechanics
  - Data.Drasil.ExternalLibraries.ODELibraries
  - Data.Drasil.Software.Products
  - Data.Drasil.Quantities.Thermodynamics
  - Data.Drasil.Quantities.PhysicalProperties
  - Data.Drasil.Quantities.Physics
  - Data.Drasil.Quantities.Math
  - Data.Drasil.Quantities.SolidMechanics
  - Data.Drasil.Units.Thermodynamics
  - Data.Drasil.Units.PhysicalProperties
  - Data.Drasil.Units.Physics
  - Data.Drasil.Units.SolidMechanics
  - Data.Drasil.Theories.Physics
