name:                drasil-gool
version:             0.1.1.0
license:             BSD3
author:              "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith, Brooks MacLachlan"
maintainer:          "Jacques Carette"
synopsis:	           A framework for code and document generation for scientific software - GOOL SubPackage
github:              JacquesCarette/Drasil
homepage:            https://jacquescarette.github.io/Drasil/

extra-source-files: []

# Metadata used when publishing your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

dependencies:
- base >= 4.7 && < 5
- lens >= 4.12
- containers >= 0.5.5.1
- pretty >= 1.1.1.1
- mtl >= 2.2.1
- directory >= 1.2.6.2
- filepath >= 1.4.1
- split >= 0.2.3.1
- MissingH >= 1.4.0.1
- data-fix (>= 0.0.4 && <= 1.0)
- data-ordlist >= 0.4.7.0
- composition
- drasil-utils

ghc-options:
- -Wall
- -Wredundant-constraints

library:
  source-dirs: ./
  exposed-modules:
  - GOOL.Drasil
