name:                drasil-code
version:             0.1.9.0
author:              "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith"
maintainer:          "Jacques Carette"
synopsis:	           A framework for code and document generation for scientific software - Code SubPackage
github:              JacquesCarette/Drasil
homepage:            https://jacquescarette.github.io/Drasil/
description:         Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- lens >= 4.12
- containers >= 0.5.5.1
- pretty >= 1.1.1.1
- mtl >= 2.2.1
- directory >= 1.2.6.2
- filepath >= 1.4.1
- split >= 0.2.3.1
- parsec >= 3.1.9
- drasil-lang
- drasil-utils
- drasil-build
- drasil-theory
- drasil-database
- drasil-printers
- drasil-gool

ghc-options:
- -Wall
- -Wredundant-constraints

library:
  source-dirs: ./
  exposed-modules:
  - Language.Drasil.Code
  - Data.Drasil.ExternalLibraries.ODELibraries
  other-modules:
    - Language.Drasil.Chunk.Code
    - Language.Drasil.Chunk.CodeDefinition
    - Language.Drasil.Chunk.Parameter
    - Language.Drasil.Code.Code
    - Language.Drasil.Code.CodeQuantityDicts
    - Language.Drasil.Code.DataDesc
    - Language.Drasil.Code.ExternalLibrary
    - Language.Drasil.Code.ExternalLibraryCall
    - Language.Drasil.Code.ExtLibImport
    - Language.Drasil.Code.Lang
    - Language.Drasil.Code.Imperative.Build.AST
    - Language.Drasil.Code.Imperative.Build.Import
    - Language.Drasil.Code.Imperative.ConceptMatch
    - Language.Drasil.Code.Imperative.SpaceMatch
    - Language.Drasil.Code.Imperative.Doxygen.Import
    - Language.Drasil.Code.Imperative.ReadInput
    - Language.Drasil.Code.Imperative.WriteInput
    - Language.Drasil.Code.Imperative.WriteReadMe
    - Language.Drasil.Code.Imperative.GOOL.Data
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.LanguagePolymorphic
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.JavaRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.PythonRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.CSharpRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.CppRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.SwiftRenderer
    - Language.Drasil.Code.Imperative.GOOL.ClassInterface
    - Language.Drasil.Code.Imperative.Comments
    - Language.Drasil.Code.Imperative.Descriptions
    - Language.Drasil.Code.Imperative.FunctionCalls
    - Language.Drasil.Code.Imperative.GenerateGOOL
    - Language.Drasil.Code.Imperative.Generator
    - Language.Drasil.Code.Imperative.GenODE
    - Language.Drasil.Code.Imperative.Helpers
    - Language.Drasil.Code.Imperative.Import
    - Language.Drasil.Code.Imperative.Logging
    - Language.Drasil.Code.Imperative.Modules
    - Language.Drasil.Code.Imperative.Parameters
    - Language.Drasil.Code.Imperative.DrasilState
    - Language.Drasil.Code.CodeGeneration
    - Language.Drasil.Data.ODEInfo
    - Language.Drasil.Data.ODELibPckg
    - Language.Drasil.Choices
    - Language.Drasil.CodeExpr
    - Language.Drasil.CodeSpec
    - Language.Drasil.Mod

executables:
  codegenTest:
    main: Test.Main
    source-dirs: ./
    other-modules:
    - Test.FileTests
    - Test.HelloWorld
    - Test.Helper
    - Test.Observer
    - Test.PatternTest
    - Language.Drasil.Code
    - Language.Drasil.Chunk.Code
    - Language.Drasil.Chunk.CodeDefinition
    - Language.Drasil.Chunk.Parameter
    - Language.Drasil.Code.Code
    - Language.Drasil.Code.CodeQuantityDicts
    - Language.Drasil.Code.DataDesc
    - Language.Drasil.Code.ExternalLibrary
    - Language.Drasil.Code.ExternalLibraryCall
    - Language.Drasil.Code.ExtLibImport
    - Language.Drasil.Code.Lang
    - Language.Drasil.Code.Imperative.Build.AST
    - Language.Drasil.Code.Imperative.Build.Import
    - Language.Drasil.Code.Imperative.ConceptMatch
    - Language.Drasil.Code.Imperative.SpaceMatch
    - Language.Drasil.Code.Imperative.Doxygen.Import
    - Language.Drasil.Code.Imperative.ReadInput
    - Language.Drasil.Code.Imperative.WriteInput
    - Language.Drasil.Code.Imperative.WriteReadMe
    - Language.Drasil.Code.Imperative.GOOL.Data
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.LanguagePolymorphic
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.JavaRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.PythonRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.CSharpRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.CppRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.SwiftRenderer
    - Language.Drasil.Code.Imperative.GOOL.ClassInterface
    - Language.Drasil.Code.Imperative.Comments
    - Language.Drasil.Code.Imperative.Descriptions
    - Language.Drasil.Code.Imperative.FunctionCalls
    - Language.Drasil.Code.Imperative.GenerateGOOL
    - Language.Drasil.Code.Imperative.Generator
    - Language.Drasil.Code.Imperative.GenODE
    - Language.Drasil.Code.Imperative.Helpers
    - Language.Drasil.Code.Imperative.Import
    - Language.Drasil.Code.Imperative.Logging
    - Language.Drasil.Code.Imperative.Modules
    - Language.Drasil.Code.Imperative.Parameters
    - Language.Drasil.Code.Imperative.DrasilState
    - Language.Drasil.Code.CodeGeneration
    - Language.Drasil.Data.ODEInfo
    - Language.Drasil.Data.ODELibPckg
    - Language.Drasil.Choices
    - Language.Drasil.CodeExpr
    - Language.Drasil.CodeSpec
    - Language.Drasil.Mod
    ghc-options:
    - -threaded
    - -O2
    dependencies:	
    - drasil-code
