on: 
  push:
    branches-ignore: master
  pull_request:
    branches-ignore: master
name: Drasil
defaults:
  run:
    shell: bash
    working-directory: code
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Haskell Stack"
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true
          stack-version: 'latest'
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-store-${{ hashFiles('stack.yaml') }}
      - name: "HLint"
        run: curl --max-time 60 -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
      - name: "Install dependencies"
        run: stack --no-terminal test --bench --only-dependencies
      - name: "Build"
        run: make prog stackArgs="--no-terminal"
      - name: "Stable"
        run: make stackArgs="--no-terminal" NOISY=yes
