on: 
  push:
    branches-ignore: master
  pull_request:
    branches: master
  workflow_dispatch:
name: Drasil
defaults:
  run:
    shell: bash
    working-directory: code
jobs:
  build:
    name: "Build"
    if: |
      github.event_name == 'pull_request'
      || github.event_name == 'workflow_dispatch'
      || (github.event_name == 'push' && contains(github.event.head_commit.message, '[workflow-trigger]'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Update apt package list"
        run: sudo apt-get update
      - name: "Install system requirements"
        run: sudo apt-get install -y libgmp-dev python3 graphviz doxygen fonts-lmodern texlive-bibtex-extra texlive-latex-extra texlive-science texlive-xetex texlive-luatex g++ default-jdk mono-devel
      - name: "Install Stack"
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true
          stack-version: 'latest'
      - name: "Cache dependencies"
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            ~/.cabal/packages
            ~/.cabal/store
            code/.stack-work/
            ~/.local/bin/graphmod
          key: ${{ runner.os }}-store-${{ hashFiles('code/stack.yaml') }}
      - name: "Update PATH"
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.swift/usr/bin" >> $GITHUB_PATH
      - name: "HLint"
        run: curl --max-time 60 -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
      - name: "Install dependencies"
        run: stack --no-terminal test --bench --only-dependencies
      - name: "Build"
        # TODO: Add back -Werror flag to stackArgs
        run: make prog stackArgs="--no-terminal"
      - name: "Stable"
        run: make stackArgs="--no-terminal" NOISY=yes
      - name: "TeX"
        run: make tex SUMMARIZE_TEX=yes
      - name: "Code"
        run: make code
      - name: "Doxygen"
        run: make doxygen
      - name: "Docs"
        run: make docs haddockArgs="--no-haddock-deps --no-haddock-hyperlink-source"
      - name: "Graphs"
        run: make graphs
      - name: "Test Deploy"
        run: sh scripts/maybe_test_deploy.sh
