on: [push, pull_request]
name: Drasil
jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-version: 'latest'
      - run: cd code && make prog stackArgs="--no-terminal"